### ISSUE TITLE
권장 방법으로 도커실행시 set.json 파일이 없다고 뜨네요.

### ISSUE THREAD

**Issue by midduck** [Make-openNAMU/openNAMU-Guide#1]
권장 방법으로 도커실행시 set.json 파일이 없다고 뜨네요. 
set.json 파일은 어떤 방식으로 작성해야 하는지, 환경변수는 어떤걸 설정해 주어야 하나요

**Comment by surplus-dev** [comment]
버전이 몇 인가요? 최신 오픈나무 버전의 경우에는 set.json을 사용하지 않도록 변경되어서 말이죠

**Comment by midduck** [comment]
@2du 버전은 별도의 tag를 달지 않았습니다. 

```
version : v3.0.8-stable-99
db name : Traceback (most recent call last):
  File "app.py", line 24, in <module>
    json_data = open('set.json').read()
FileNotFoundError: [Errno 2] No such file or directory: 'set.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 30, in <module>
    new_json = str(input())
EOFError: EOF when reading a line
```


이런식으로 에러가 발생하네요.

**Comment by surplus-dev** [comment]
아마 stable 버전은 도커 기능이 완전하지 않아서 그럴껍니다

set.json이란 파일을 openNAMU 폴더에 만들고 이렇게 작성하세요

```json
{ "db" : "data" } 
```

**Comment by ShapeLayer** [comment]
도커에서 공유 폴더를 생성하면 그 안에 있는 내용은 전부 삭제됩니다. 그 때문에 set.json을 오픈나무가 열지 못한것 같습니다.

그걸 위해 도커 호스트에서 공유 폴더에 별도 파일을 추가하는 작업을 해야하고, Docker Install 가이드에 그 과정까지 대략적인 워크플로우를 명시해뒀던것 같은데.. 좀 더 자세히 언급하도록 하겠습니다.

https://github.com/Make-openNAMU/openNAMU-Guide/blob/master/articles/ko-kr/docker-install.md#ii-%EB%8F%84%EC%BB%A4-%EC%8B%9C%EC%9E%91

**Comment by surplus-dev** [comment]
음... 다시 확인해보니 stable에선 도커를 못 돌릴 것 같네요 master 버전을 사용해주세요
