### ISSUE TITLE
[질문] 최초 실행 시 설정해야 하는 항목들에 대한 설명도 있었으면 합니다

### ISSUE THREAD

**Issue by HotoRas** [Make-openNAMU/openNAMU-Guide#3]
~~당연히 그래야겠지만~~ 최초 실행 시 설정해야 하는 항목들까지 다 있으면 좋을 것 같습니다.

[오픈테섭](https://2du.pythonanywhere.com) 회원가입이 막혀있는 관계로 여기에 이슈 올립니다.   
오픈나무 메인 레포에 올리는 건 실례인 것 같아서 여기에 올리는 거니 불편하시더라도 양해 부탁드립니다.

**Comment by surplus-dev** [comment]
사실 이 레포를 중지 시키고 오픈테섭으로 병합하고 싶은데 매우 귀찮이즘 때문에 진행이 안되고 있습니다

덤으로 오픈나무 본 레포에 올리셔도 상관 없습니다
